services:
  werkint_mutex.mutexmanager:
    class: Werkint\Bundle\MutexBundle\Service\MutexManager
    arguments:
      - @=parameter('werkint_mutex')['lockfiles_dir']

  werkint_mutex.semlock.annotation_driver:
    class: Werkint\Bundle\MutexBundle\Service\SemLock\Metadata\AnnotationDriver
    arguments:
      - @annotation_reader
  werkint_mutex.semlock.metadata_factory:
    class: Metadata\MetadataFactory
    arguments:
      - @werkint_mutex.semlock.annotation_driver
  werkint_mutex.semlock.pointcut:
    class: Werkint\Bundle\MutexBundle\Service\SemLock\Pointcut\SemLockPointcut
    arguments:
      - @werkint_mutex.semlock.metadata_factory
      - %kernel.debug%
    tags:
      - { name: jms_aop.pointcut, interceptor: werkint_mutex.semlock.interceptor }
  werkint_mutex.semlock.interceptor:
    class: Werkint\Bundle\MutexBundle\Service\SemLock\Pointcut\PointcutInterceptor
    arguments:
      - @werkint_mutex.semlock.metadata_factory
      - @werkint_mutex.mutexmanager
